export const shopProducts = [
    {
        imageSrc: 'assets/images/products/product1.jpg',
        category: 'Product Design',
        title: 'Creative Web Page Design',
        rating: 5,
        price: '$593',
    },
    {
        imageSrc: 'assets/images/products/product2.jpg',
        category: 'Product Design',
        title: 'Task Management Dashboard',
        rating: 5,
        price: '$640',
    },
    {
        imageSrc: 'assets/images/products/product3.jpg',
        category: 'Product Design',
        title: 'Mobile Application Design',
        rating: 5,
        price: '$866',
    },
    {
        imageSrc: 'assets/images/products/product4.jpg',
        category: 'Product Design',
        title: '3D Illustration Design',
        rating: 5,
        price: '$866',
    },
    {
        imageSrc: 'assets/images/products/product5.jpg',
        category: 'Product Design',
        title: 'Task Management Dashboard',
        rating: 5,
        price: '$866',
    },
    {
        imageSrc: 'assets/images/products/product6.jpg',
        category: 'Product Design',
        title: '3D Illustration Design',
        rating: 5,
        price: '$866',
    },
    {
        imageSrc: 'assets/images/products/product7.jpg',
        category: 'Product Design',
        title: 'T-shirt Mockup Design',
        rating: 5,
        price: '$866',
    }, 
    {
        imageSrc: 'assets/images/products/product8.jpg',
        category: 'Product Design',
        title: 'Business Card Mockup',
        rating: 5,
        price: '$866',
    }, 
    {
        imageSrc: 'assets/images/products/product9.jpg',
        category: 'Product Design',
        title: 'Logo Design Branding',
        rating: 5,
        price: '$866',
    },
];